Register form structure - Register Page - button
IgrowkerTraining/i004-pawsome-front pull request #20
Opened 2024-11-14 17:23 UTC by Melsalome

2024-11-14 19:58 UTC, COCOASOO commented on src/views/RegisterRoutes.tsx
Meter la route en el futuro layout?

2024-11-14 19:58 UTC, COCOASOO requested changes
archivo de rutas necesario?

2024-11-15 12:13 UTC, Davpad approved these changes, later dismissed

2024-11-18 09:30 UTC, closed without merging

2024-11-18 09:31 UTC, Davpad commented
Volvamos a intentarlo, necesitaba la aprobación de Adri y ya no está en el equipo